### ISSUE TITLE
US6 project-editing

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#12]
# Value proposition

As User I can edit or delete projects if my plans have changed

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/6bcd6528-4444-4d7e-8e06-c42d3b6ba8b0)

## Acceptance criteria

- [ ] An edit button in the shape of a pencil icon is displayed as part of every project card
- [ ] clickable edit button, click to go to a new page
- [ ] form of inputs similar from page/new-project
- [ ] when you click the  "Save" button, the data is added to the form and automatically return to the main page or if there is no change, the home button
- [ ] when you click the "Delete" button, the data from the form and the project itself are deleted from the main page and automatically returned to the main page

## Tasks

- [ ] Create branch feature/project-edit
- [ ] Create a new page/project-changes
- [ ] Create save button
- [ ] Create delete button
- [ ] Create home button
- [ ] Сonnection LocalStorage
- [ ] Implementation of logic that pulls existing information into the appropriate form to resave it with changes and return to the overview page
- [ ] Implementation of logic that deletes the project completely and returns to the overview page where the project is no longer there

Size: xl

**Comment by jonas8900** [comment]
i like your value proposition, your description pictures and your idea behind this user story !! The Acceptance criteria is a bit too specific in our "nerd" language, words like "form", "data is added" "card" are maybe a bit incomprehensible to someone who is not a programmer. maybe you could make it a bit more general. 

our coach told us, we should not make a user story with a large size, so maybe you can put something into another user story, so maybe the size switch to medium. 

All in all, a good userstory!
