### ISSUE TITLE
US6 US6 project-editing

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#13]
# Value proposition

As User I can edit projects if my plans have changed

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/b584b62b-0eb5-46f1-b87a-f473b22fa3fc)

## Acceptance criteria

- [ ] An edit button in the shape of a pencil icon is displayed as part of every project card
- [ ] clickable edit button

## Tasks

- [ ] Create branch feature/project-edit-button
- [ ] Create edit button
- [ ] Create design for the edit button

Size: s
