### ISSUE TITLE
US7 project-changes

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#14]
# Value proposition

As User I can edit projects form if my plans have changed

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/b05a3e81-059d-4287-b148-6d637cdedaba)

## Acceptance criteria

- [ ] when you click on the edit button, it takes us to a new page
- [ ] on the new page we already see the previously filled information
- [ ] the ability to edit information in the input fields
- [ ] the Home button allows you to return to the main page

## Tasks

- [ ] Create branch feature/project-edit-form
- [ ] Create a new page/make-changes
- [ ] Create home button
- [ ] Implementation of logic that wraps around events and returns to the overview page
Implementation of logic that pulls existing information into the appropriate form
- [ ] Implementation of logic that pulls existing information into the appropriate form
- [ ] Сonnection LocalStorage

Size: m
