### ISSUE TITLE
US8 project-delete-button

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#15]
# Value proposition

As User I can edit or delete projects if my plans have changed

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/13fd5097-288e-4b92-aab0-80e2cd55f8a4)

## Acceptance criteria

- [ ] when you click the save button, the data changes and automatically returns to the main page
- [ ] when you click the delete button, the project is deleted and we automatically return to the main page where the project is no longer there

## Tasks

- [ ] Create branch feature/project-delete-button
- [ ] Create save button
- [ ] Create delete button
- [ ] Сonnection LocalStorage
- [ ] Implementation of the logic when you click on the Save button, the information is updated and returns us to the overview page
- [ ] Implementation of logic that completely deletes the project and returns to the overview page

Size: l
