### ISSUE TITLE
US4

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#8]
# Value proposition

As a user I do not want to make unnecessary movements to find out specific aspects of my project, I want to see them immediately

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/207b9d30-9630-4673-a39d-e58be7dcdc0f)

## Acceptance criteria

- [ ] Label Size/ Label Due by: not clickable and is for informational purposes only
- [ ] Label Size/ Label Due by: displays information that was previously entered when creating a project from the Size/Due by input form
- [ ] Label Size/ Label Due by: the displayed information is up-to-date and updated after each editing of the project

## Tasks

- [ ] Create branch feature/projects-labels
- [ ] Create a label Size for project based on data taken from /project-form/form of Size input
- [ ] Create a label Due by for project based on data taken from /project-form/form of Due by input

Size: L
