### ISSUE TITLE
US5 project-checkbox

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Andrii-PM#9]
# Value proposition

As a user I want to be able to mark a project as complete, so that I know which projects are unfinished or ongoing.

## Description

![image](https://github.com/AndryBasaraba/Andrii-PM/assets/135517142/cce6eee7-ee1c-421f-bd69-da31d7374071)

## Acceptance criteria

- [ ] The checkbox is rendered as part of each project card
- [ ] The checkbox can be checked and unchecked
- [ ] When the checkbox is checked, the project name is in the state completed

## Tasks

- [ ] Create branch feature/project-checkbox
- [ ] Create an input with the type checkbox
- [ ] Add a boolean flag to the project object checked: true/false
- [ ] Change the title of projects when checkbox is checked
- [ ] Implement logic that handles updating the project object when the checkbox is checked/unchecked

Size: m

**Comment by CJAkkuec** [comment]
With all due respect ...
> user choices are accompanied by visual cues, ensuring user are always aware of him decisions. Dynamic changes detect high speed communication and user are never left wondering if user selections have passed.

I have 0 clue what that means. 😂 

What does the checkbox do? Is it to mark the project as "complete"?

If so, allow me to make some suggestions ...

The point of the value proposition is to outline the benefit the feature has from a user perspective.

**Value Proposition**
> As a user I want to be able to mark a project as complete, so that I know which projects are unfinished or ongoing.

That would be a more apt value proposition for this user story.

**Acceptance Criteria**
As far as the acceptance criteria are concerned, you can probably get rid of all of them and just list something like

> A checkbox is rendered as part of each project card
> The checkbox can be checked and unchecked

**Tasks**
... which brings us to the tasks:

> Create branch feature/project-checkbox
> Create an input with the type checkbox
> Add a boolean flag to the project object `checked: true/false`
> Implement logic that handles updating the project object when the checkbox is checked/unchecked

**Comment by AndryBasaraba** [comment]
Thanks for checking. 

> user choices are accompanied by visual cues, ensuring user are always aware of him decisions. Dynamic changes detect high speed communication and user are never left wondering if user selections have passed.

I'm being honest, i wrote it with ChatGPT
